### ISSUE TITLE
Improve JSDoc

### ISSUE THREAD

**Issue by JoseLion** [stackbuilders/assertive-ts#41]
As the API reference will be auto-generated with [TypeDoc](https://typedoc.org/), we want to improve the JSDoc to add more information to the documentation. we want to add the following changes:

- [x] Add JSDoc to all assertion classes
- [x] Add `@param` to all generic types
- [ ] Add `@example` to all assertion matcher methods to show their usage in the documentation
- [x] Change `@link` of built-in data types to link to the official JavaScript documentation.
  - For instance, `{@link Error}` should point to the [MDN Error docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)

**Comment by NeoLight1010** [comment]
Hello! I'm currently working on this issue and will be sending a PR in the following days :smile:
