### ISSUE TITLE
Docs page seem to be broken

### ISSUE THREAD

**Issue by ibarrae** [stackbuilders/assertive-ts#59]
The docs URL seems to be broken and it's displaying a 404 https://stackbuilders.github.io/assertive-ts/docs/build/

**Comment by JoseLion** [comment]
Thanks for the report @ibarrae! This should be fixed now with release `v1.1.0`. Please let me know if it works for you as well. I'll be on the watch just in case 🙂

**Comment by ibarrae** [comment]
Yes, it's working now! Thanks a bunch @JoseLion
